NS-BRKGA: NSBRKGA::NSBRKGA< Decoder > Class Template Reference
NSBRKGA::NSBRKGA< Decoder > Class Template Reference
Non-dominated Sorting Biased Random-Key Genetic Algorithm with Multi-Parent crossover and Implicit Path Relinking.
#include <nsbrkga.hpp>
Public Member Functions
Constructors and destructor
NSBRKGA (Decoder &decoder_reference, const std::vector< Sense > senses, const unsigned seed, const unsigned chromosome_size, const NsbrkgaParams &params, const unsigned max_threads=1, const bool evolutionary_mechanism_on=true)
Constructs the algorithm and allocates internal data structures.
~NSBRKGA ()
Destructor.
Initialization methods
void setInitialPopulations (const std::vector< std::vector< Chromosome >> &populations)
Sets individuals to initial population.
void setBiasCustomFunction (const std::function< double(const unsigned)> &func)
Sets a custom bias function used to build the probabilities.
void setDiversityCustomFunction (const std::function< double(const std::vector< std::vector< double >> &)> &func)
Sets a custom diversity function used to build the elite set.
void initialize ()
Initializes the populations and others parameters of the algorithm.
Evolution
bool evolve (unsigned generations=1)
Evolves the current populations following the guidelines of NSBRKGAs.
Path relinking
PathRelinking::PathRelinkingResult pathRelink (PathRelinking::Type pr_type, std::shared_ptr< DistanceFunctionBase > dist, long max_time=0, double percentage=1.0)
Performs path relinking between elite solutions that are, at least, a given minimum distance between themselves. In this method, the local/loaded parameters are ignored in favor to the supplied ones.
PathRelinking::PathRelinkingResult pathRelink (std::shared_ptr< DistanceFunctionBase > dist, long max_time=0, double percentage=1.0)
Performs path relinking between elite solutions that are, at least, a given minimum distance between themselves.
Population manipulation methods
void exchangeElite (unsigned num_immigrants)
Exchanges elite-solutions between the populations.
void reset (double intensity=0.5, unsigned population_index=std::numeric_limits< unsigned >::infinity())
Resets all populations with brand new keys.
void shake (double intensity=0.5, double distribution=20.0, unsigned population_index=std::numeric_limits< unsigned >::infinity())
Performs a shaking in the chosen population.
void injectChromosome (const Chromosome &chromosome, unsigned population_index, unsigned position)
Injects a chromosome and its fitness into a population in the given place position.
Support methods
const Population & getCurrentPopulation (unsigned population_index=0) const
Returns a reference to a current population.
const std::vector< std::pair< std::vector< double >, Chromosome > > & getIncumbentSolutions () const
Returns the solutions with non-dominated fitness found so far.
std::vector< Chromosome > getIncumbentChromosomes () const
Returns the chromosomes with non-dominated fitness found so far.
std::vector< std::vector< double > > getIncumbentFitnesses () const
Return the non-dominated fitness found so far.
const Chromosome & getChromosome (unsigned population_index, unsigned position) const
Returns a reference to a chromosome of the given population.
std::vector< double > getFitness (unsigned population_index, unsigned position) const
Returns the fitness of a chromosome of the given population.
Parameter getters
const NsbrkgaParams & getNsbrkgaParams () const
std::vector< Sense > getOptimizationSenses () const
unsigned getChromosomeSize () const
unsigned getMinNumElites () const
unsigned getMaxNumElites () const
bool evolutionaryIsMechanismOn () const
unsigned getMaxThreads () const
Protected Member Functions
Helper functions
bool dominates (const std::vector< double > a1, const std::vector< double > a2) const
Returns true if a1 dominates a2.
double rand01 ()
Generates a random double-precision floating-point number uniformly distributed in the range [0, 1).
uint_fast32_t randInt (const uint_fast32_t n)
Generates a uniformly distributed random integer in the range [0, n].
Protected Attributes
BRKGA Hyper-parameters
NsbrkgaParams params
The BRKGA and IPR hyper-parameters.
const std::vector< Sense > OPT_SENSES
Indicates whether we are maximizing or minimizing each objective.
const unsigned CHROMOSOME_SIZE
Number of genes in the chromosome.
unsigned min_num_elites
Minimum number of elite individuals in each population.
unsigned max_num_elites
Maximum number of elite individuals in each population.
bool evolutionary_mechanism_on
If false, no evolution is performed but only chromosome decoding. Very useful to emulate a multi-start algorithm.
Parallel computing parameters
const unsigned MAX_THREADS
Number of threads for parallel decoding.
Engines
Decoder & decoder
Reference to the problem-dependent Decoder.
std::mt19937 rng
Mersenne twister random number generator.
Algorithm data
std::vector< std::shared_ptr< Population > > previous
Previous populations.
std::vector< std::shared_ptr< Population > > current
Current populations.
std::function< double(const unsigned)> bias_function
Reference for the bias function.
std::function< double(const std::vector< std::vector< double >> &)> diversity_function
Reference for the diversity function.
double total_bias_weight
Holds the sum of the results of each raking given a bias function. This value is needed to normalization.
std::vector< unsigned > shuffled_individuals
Used to shuffled individual/chromosome indices during the selection.
std::vector< unsigned > parents_indexes
Used to select the parents for the mating.
std::vector< std::pair< std::vector< double >, unsigned > > parents_ordered
Defines the order of parents during the mating.
bool initial_populations
Indicates if initial populations are set.
bool initialized
Indicates if the algorithm was proper initialized.
std::chrono::system_clock::time_point pr_start_time
Holds the start time for a call of the path relink procedure.
std::vector< std::pair< std::vector< double >, Chromosome > > incumbent_solutions
The current best solutions.
void selectParents (const Population &curr, const size_t &chr, const bool use_best_individual=false)
void polynomialMutation (double &allele, double mutation_probability, double mutation_distribution)
Applies polynomial mutation to a single allele value.
void polynomialMutation (double &allele, double mutation_probability)
void polynomialMutation (double &allele)
void mate (const Population &curr, Chromosome &offspring)
Core local methods
bool evolution (Population &curr, Population &next)
Evolves the current population to the next.
std::pair< std::vector< double >, Chromosome > allocationPathRelink (const std::pair< std::vector< double >, Chromosome > &solution1, const std::pair< std::vector< double >, Chromosome > &solution2, long max_time, double percentage, std::vector< std::pair< std::vector< double >, Chromosome >> &best_solutions)
Performs the direct path relinking.
std::pair< std::vector< double >, Chromosome > permutationPathRelink (const std::pair< std::vector< double >, Chromosome > &solution1, const std::pair< std::vector< double >, Chromosome > &solution2, long max_time, double percentage, std::vector< std::pair< std::vector< double >, Chromosome >> &best_solutions)
Performs the permutation-based path relinking.
std::pair< std::vector< double >, Chromosome > binarySearchPathRelink (const std::pair< std::vector< double >, Chromosome > &solution1, const std::pair< std::vector< double >, Chromosome > &solution2, long max_time, std::vector< std::pair< std::vector< double >, Chromosome >> &best_solutions)
Performs the binary-search-based path relinking.
bool updateIncumbentSolutions (const std::vector< std::pair< std::vector< double >, Chromosome >> &newSolutions)
Updates the incumbent (best known) solutions with new candidate solutions.
static bool updateIncumbentSolutions (std::vector< std::pair< std::vector< double >, Chromosome >> &incumbent_solutions, const std::vector< std::pair< std::vector< double >, Chromosome >> &new_solutions, const std::vector< Sense > &senses, const std::size_t max_num_solutions=0)
Detailed Description
template<class Decoder>
class NSBRKGA::NSBRKGA< Decoder >
Non-dominated Sorting Biased Random-Key Genetic Algorithm with Multi-Parent crossover and Implicit Path Relinking.
Template Parameters
Decoder A class or functor providing the decoding interface. It must expose:
std::vector<double> decode(NSBRKGA::Chromosome &chromosome,
                           bool rewrite);
decode() maps a chromosome (random-key vector in \([0,1)^n\)) to a vector of objective values. When rewrite == true the decoder may overwrite the chromosome alleles (Lamarckian write-back); all modified alleles must remain in \([0,1)\). When rewrite == false the chromosome must not be modified. If max_threads > 1, decode() must be thread-safe.
Design and invariants
Chromosome
Each chromosome is a std::vector<double> of length \(n\) (the problem dimension), with alleles in \([0, 1)\). The library guarantees that all generated alleles are initialised in \([0,1)\) and that polynomial mutation keeps them in that range.
Elite set
After each generation, non-dominated sorting assigns solutions to Pareto fronts. All front-0 solutions are elite; additional solutions from subsequent fronts may be added using the diversity function until the elite set size is in [min_num_elites, max_num_elites].
Multi-objective handling
Optimization senses are given as std::vector<Sense>, one per objective. Non-dominated sorting uses these senses to determine dominance: solution \(a\) dominates \(b\) when \(a\) is at least as good as \(b\) in every objective and strictly better in at least one. Within each Pareto front, solutions are ordered by decreasing crowding distance (NSGA-II strategy) to maintain diversity.
Thread safety
Population decoding inside evolve() and initialize() is parallelised via OpenMP. The library guarantees that each call to Decoder::decode() operates on a distinct chromosome object; however, any shared mutable state in the decoder (e.g., problem data structures) must be protected by the user. A common safe pattern is to use only const/read-only shared data and keep all working memory in local (stack-allocated) variables.
Path relinking
Implicit Path Relinking (IPR) navigates from a base chromosome to a guiding chromosome by iteratively selecting and applying the move that brings the base closest to the guide. Three strategies are available (see PathRelinking::Type). During relinking, decode() is called with rewrite = false to preserve the search path. A final call with rewrite = true is issued on the best chromosome found.
Minimal usage example
#include "nsbrkga/nsbrkga.hpp"
// Problem-specific decoder.
struct MyDecoder {
    // Returns {objective_value}.
    std::vector<double> decode(NSBRKGA::Chromosome &chr, bool) const {
        double cost = 0.0;
        for (double allele : chr) { cost += allele; }  // trivial example
        return {cost};
    }
};
int main() {
    auto [params, ctrl] =
        NSBRKGA::readConfiguration("brkga.cfg");
    MyDecoder decoder;
    NSBRKGA::NSBRKGA<MyDecoder> algo(
        decoder,
        {NSBRKGA::Sense::MINIMIZE},  // one objective, minimise
        42,                          // RNG seed
        100,                         // chromosome size
        params);
    algo.initialize();
    for (unsigned gen = 0; gen < 200; ++gen) {
        algo.evolve();  // one generation
        if (ctrl.exchange_interval > 0 &&
            gen % ctrl.exchange_interval == 0) {
            algo.exchangeElite(ctrl.num_exchange_individuals);
        }
    }
    for (auto &[fitness, chrom] : algo.getIncumbentSolutions()) {
        std::cout << "fitness: " << fitness[0] << "\n";
    }
}
History
Based on the original BRKGA code by Rodrigo Franco Toso (2011). http://github.com/rfrancotoso/brkgaAPI
See also
NSBRKGA::Chromosome
NSBRKGA::NsbrkgaParams
NSBRKGA::ExternalControlParams
NSBRKGA::BiasFunctionType
NSBRKGA::CrossoverType
NSBRKGA::PathRelinking::Type
NSBRKGA::DistanceFunctionBase
Definition at line 1883 of file nsbrkga.hpp.
Constructor & Destructor Documentation
NSBRKGA()
template<class Decoder > NSBRKGA::NSBRKGA< Decoder >::NSBRKGA (Decoder & decoder_reference, const std::vector< Sense > senses, const unsigned seed, const unsigned chromosome_size, const NsbrkgaParams & params, const unsigned max_threads = 1, const bool evolutionary_mechanism_on = true)
Constructs the algorithm and allocates internal data structures.
All data in params is copied; the caller may discard or modify the object after construction. The constructor validates all parameter combinations and throws std::range_error on any violation.
Parameters
decoder_reference reference to the user-supplied decoder object. The algorithm stores a reference — the decoder must outlive the NSBRKGA instance.
senses vector of optimization senses, one per objective. E.g. {Sense::MINIMIZE, Sense::MAXIMIZE} for a bi-objective problem where the first objective is minimised and the second is maximised.
seed seed for the Mersenne Twister RNG.
chromosome_size number of alleles \(n\) in each chromosome; must be \(\ge 1\).
params algorithm hyper-parameters; see NsbrkgaParams.
max_threads number of OpenMP threads for parallel decoding. **Decoder::decode() must be thread-safe when > 1.** Default: 1 (serial).
evolutionary_mechanism_on when false, the elite set is forced to size 1 and all other individuals are mutants, effectively turning the algorithm into a multi-start random restart. Useful for benchmarking decoders. Default: true.
Exceptions
std::range_error if any parameter value or combination is invalid (e.g., zero chromosome size, zero population, elite bounds crossed, invalid parent counts).
See also
NSBRKGA::NsbrkgaParams
NSBRKGA::Sense
Definition at line 2564 of file nsbrkga.hpp.
References NSBRKGA::AVERAGE_DISTANCE_BETWEEN_ALL_PAIRS, NSBRKGA::AVERAGE_DISTANCE_TO_CENTROID, NSBRKGA::NsbrkgaParams::bias_type, NSBRKGA::CBRT, NSBRKGA::CONSTANT, NSBRKGA::CUBIC, NSBRKGA::NsbrkgaParams::diversity_type, NSBRKGA::EXPONENTIAL, NSBRKGA::LINEAR, NSBRKGA::LOGINVERSE, NSBRKGA::NsbrkgaParams::mutation_distribution, NSBRKGA::NsbrkgaParams::mutation_probability, NSBRKGA::NONE, NSBRKGA::NsbrkgaParams::num_independent_populations, NSBRKGA::NsbrkgaParams::population_size, NSBRKGA::POWER_MEAN_BASED, NSBRKGA::NsbrkgaParams::pr_percentage, NSBRKGA::QUADRATIC, NSBRKGA::SQRT, and NSBRKGA::NsbrkgaParams::total_parents.
~NSBRKGA()
template<class Decoder > NSBRKGA::NSBRKGA< Decoder >::~NSBRKGA () inline
Destructor.
Definition at line 1927 of file nsbrkga.hpp.
Member Function Documentation
allocationPathRelink()
template<class Decoder > std::pair< std::vector< double >, Chromosome > NSBRKGA::NSBRKGA< Decoder >::allocationPathRelink (const std::pair< std::vector< double >, Chromosome > & solution1, const std::pair< std::vector< double >, Chromosome > & solution2, long max_time, double percentage, std::vector< std::pair< std::vector< double >, Chromosome >> & best_solutions) protected
Performs the direct path relinking.
This method changes each allele or block of alleles of base chromosome for the correspondent one in the guide chromosome.
This method is a multi-thread implementation. Instead of to build and decode each chromosome one at a time, the method builds a list of candidates, altering the alleles/keys according to the guide solution, and then decode all candidates in parallel. Note that O(chromosome_size^2) additional memory is necessary to build the candidates, which can be costly if the chromosome_size is very large.
Parameters
solution1 first solution (fitness–chromosome pair).
solution2 second solution (fitness–chromosome pair).
max_time abort path relinking when reach max_time. If max_time <= 0, no limit is imposed.
percentage define the size, in percentage, of the path to build.
[out] best_solutions the best solutions found in the search.
Returns
the best solution found in the search.
Definition at line 3983 of file nsbrkga.hpp.
References NSBRKGA::MAXIMIZE, and NSBRKGA::NsbrkgaParams::num_incumbent_solutions.
binarySearchPathRelink()
template<class Decoder > std::pair< std::vector< double >, Chromosome > NSBRKGA::NSBRKGA< Decoder >::binarySearchPathRelink (const std::pair< std::vector< double >, Chromosome > & solution1, const std::pair< std::vector< double >, Chromosome > & solution2, long max_time, std::vector< std::pair< std::vector< double >, Chromosome >> & best_solutions) protected
Performs the binary-search-based path relinking.
Parameters
solution1 first solution (fitness–chromosome pair).
solution2 second solution (fitness–chromosome pair).
max_time abort path relinking when reach max_time. If max_time <= 0, no limit is imposed.
[out] best_solutions the best solutions found in the search.
Returns
the best solution found in the search.
Definition at line 4466 of file nsbrkga.hpp.
References NSBRKGA::MAXIMIZE, and NSBRKGA::NsbrkgaParams::num_incumbent_solutions.
dominates()
template<class Decoder > bool NSBRKGA::NSBRKGA< Decoder >::dominates (const std::vector< double > a1, const std::vector< double > a2) const inline protected
Returns true if a1 dominates a2.
Definition at line 2814 of file nsbrkga.hpp.
References NSBRKGA::Population::dominates().
evolution()
template<class Decoder > bool NSBRKGA::NSBRKGA< Decoder >::evolution (Population & curr, Population & next) protected
Evolves the current population to the next.
Note that the next population will be re-populate completely.
Parameters
[in] curr current population.
[out] next next population.
Definition at line 3652 of file nsbrkga.hpp.
References NSBRKGA::Population::fitness, NSBRKGA::Population::getChromosome(), NSBRKGA::Population::num_elites, NSBRKGA::Population::population, NSBRKGA::NsbrkgaParams::population_size, NSBRKGA::Population::setFitness(), and NSBRKGA::Population::sortFitness().
evolutionaryIsMechanismOn()
template<class Decoder > bool NSBRKGA::NSBRKGA< Decoder >::evolutionaryIsMechanismOn () const inline
Definition at line 2258 of file nsbrkga.hpp.
evolve()
template<class Decoder > bool NSBRKGA::NSBRKGA< Decoder >::evolve (unsigned generations = 1)
Evolves the current populations following the guidelines of NSBRKGAs.
Warning
The decoding is done in parallel using threads, and the user must guarantee that the decoder is THREAD-SAFE. If such property cannot be held, we suggest using a single thread for optimization.
Parameters
generations number of generations to be evolved. Must be larger than zero.
Exceptions
std::runtime_error if the algorithm is not initialized.
std::range_error if the number of generations is zero.
Definition at line 3112 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::num_independent_populations.
exchangeElite()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::exchangeElite (unsigned num_immigrants)
Exchanges elite-solutions between the populations.
Given a population, the num_immigrants best solutions are copied to the neighbor populations, replacing their worth solutions. If there is only one population, nothing is done.
Parameters
num_immigrants number of elite chromosomes to select from each population.
Exceptions
std::range_error if the number of immigrants less than one or it is larger than or equal to the population size divided by the number of populations minus one, i.e. \(\lceil \frac{population\_size}{num\_independent\_populations} \rceil - 1\).
Definition at line 3157 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::num_independent_populations, and NSBRKGA::NsbrkgaParams::population_size.
getChromosome()
template<class Decoder > const Chromosome & NSBRKGA::NSBRKGA< Decoder >::getChromosome (unsigned population_index, unsigned position) const
Returns a reference to a chromosome of the given population.
Parameters
population_index the population index.
position the chromosome position, ordered by fitness. The best chromosome is located in position 0.
Exceptions
std::range_error either if population_index is larger than number of populations, or position is larger than the population size.
Definition at line 2914 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::population_size.
getChromosomeSize()
template<class Decoder > unsigned NSBRKGA::NSBRKGA< Decoder >::getChromosomeSize () const inline
Definition at line 2252 of file nsbrkga.hpp.
getCurrentPopulation()
template<class Decoder > const Population & NSBRKGA::NSBRKGA< Decoder >::getCurrentPopulation (unsigned population_index = 0) const
Returns a reference to a current population.
Parameters
population_index the population index.
Exceptions
std::range_error if the index is larger than number of populations.
Definition at line 2829 of file nsbrkga.hpp.
getFitness()
template<class Decoder > std::vector< double > NSBRKGA::NSBRKGA< Decoder >::getFitness (unsigned population_index, unsigned position) const
Returns the fitness of a chromosome of the given population.
Parameters
population_index the population index.
position the chromosome position, ordered by fitness. The best chromosome is located in position 0.
Exceptions
std::range_error either if population_index is larger than number of populations, or position is larger than the population size.
Definition at line 2887 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::population_size.
getIncumbentChromosomes()
template<class Decoder > std::vector< Chromosome > NSBRKGA::NSBRKGA< Decoder >::getIncumbentChromosomes
Returns the chromosomes with non-dominated fitness found so far.
Definition at line 2856 of file nsbrkga.hpp.
getIncumbentFitnesses()
template<class Decoder > std::vector< std::vector< double > > NSBRKGA::NSBRKGA< Decoder >::getIncumbentFitnesses
Return the non-dominated fitness found so far.
Definition at line 2842 of file nsbrkga.hpp.
getIncumbentSolutions()
template<class Decoder > const std::vector< std::pair< std::vector< double >, Chromosome > > & NSBRKGA::NSBRKGA< Decoder >::getIncumbentSolutions
Returns the solutions with non-dominated fitness found so far.
Definition at line 2871 of file nsbrkga.hpp.
getMaxNumElites()
template<class Decoder > unsigned NSBRKGA::NSBRKGA< Decoder >::getMaxNumElites () const inline
Definition at line 2256 of file nsbrkga.hpp.
getMaxThreads()
template<class Decoder > unsigned NSBRKGA::NSBRKGA< Decoder >::getMaxThreads () const inline
Definition at line 2262 of file nsbrkga.hpp.
getMinNumElites()
template<class Decoder > unsigned NSBRKGA::NSBRKGA< Decoder >::getMinNumElites () const inline
Definition at line 2254 of file nsbrkga.hpp.
getNsbrkgaParams()
template<class Decoder > const NsbrkgaParams& NSBRKGA::NSBRKGA< Decoder >::getNsbrkgaParams () const inline
Definition at line 2246 of file nsbrkga.hpp.
getOptimizationSenses()
template<class Decoder > std::vector<Sense> NSBRKGA::NSBRKGA< Decoder >::getOptimizationSenses () const inline
Definition at line 2248 of file nsbrkga.hpp.
initialize()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::initialize
Initializes the populations and others parameters of the algorithm.
If a initial population is supplied, this method completes the remain individuals, if they do not exist. This method also performs the initial decoding of the chromosomes. Therefore, depending on the decoder implementation, this can take a while, and the user may want to time such procedure in his/her experiments.
Warning
This method must be call before any evolutionary or population handling method.
As it is in evolve(), the decoding is done in parallel using threads, and the user must guarantee that the decoder is THREAD-SAFE. If such property cannot be held, we suggest using a single thread for optimization.
Definition at line 3299 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::num_independent_populations, and NSBRKGA::NsbrkgaParams::population_size.
injectChromosome()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::injectChromosome (const Chromosome & chromosome, unsigned population_index, unsigned position)
Injects a chromosome and its fitness into a population in the given place position.
If fitness is not provided (fitness == Inf), the decoding is performed over chromosome. Once the chromosome is injected, the population is re-sorted according to the chromosomes' fitness.
Parameters
chromosome the chromosome to be injected.
population_index the population index.
position the chromosome position.
Exceptions
std::range_error either if population_index is larger than number of populations; or position is larger than the population size; or chromosome.size() != chromosome_size
Definition at line 2948 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::population_size.
mate()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::mate (const Population & curr, Chromosome & offspring) private
Definition at line 3569 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::crossover_type, NSBRKGA::GEOMETRIC, NSBRKGA::ROULETTE, and NSBRKGA::NsbrkgaParams::total_parents.
pathRelink() [1/2]
template<class Decoder > PathRelinking::PathRelinkingResult NSBRKGA::NSBRKGA< Decoder >::pathRelink (PathRelinking::Type pr_type, std::shared_ptr< DistanceFunctionBase > dist, long max_time = 0, double percentage = 1.0)
Performs path relinking between elite solutions that are, at least, a given minimum distance between themselves. In this method, the local/loaded parameters are ignored in favor to the supplied ones.
In the presence of multiple populations, the path relinking is performed between elite chromosomes from different populations, in a circular fashion. For example, suppose we have 3 populations. The framework performs 3 path relinkings: the first between individuals from populations 1 and 2, the second between populations 2 and 3, and the third between populations 3 and 1. In the case of just one population, both base and guiding individuals are sampled from the elite set of that population.
Note that the algorithm tries to find a pair of base and guiding solutions with a minimum distance given by the distance function. If this is not possible, a new pair of solutions are sampled (without replacement) and tested against the distance. In case it is not possible to find such pairs for the given populations, the algorithm skips to the next pair of populations (in a circular fashion, as described above). Yet, if such pairs are not found in any case, the algorithm declares failure. This indicates that the populations are very homogeneous.
If the found solution is the best solution found so far, IPR replaces the worst solution by it. Otherwise, IPR computes the distance between the found solution and all other solutions in the elite set, and replaces the worst solution by it if and only if the found solution is, at least, minimum_distance from all them.
The API will call Decoder::decode() function always with rewrite = false. The reason is that if the decoder rewrites the chromosome, the path between solutions is lost and inadvertent results may come up. Note that at the end of the path relinking, the method calls the decoder with rewrite = true in the best chromosome found to guarantee that this chromosome is re-written to reflect the best solution found.
This method is a multi-thread implementation. Instead of to build and decode each chromosome one at a time, the method builds a list of candidates, altering the alleles/keys according to the guide solution, and then decode all candidates in parallel. Note that O(chromosome_size^2 / block_size) additional memory is necessary to build the candidates, which can be costly if the chromosome_size is very large.
Warning
As it is in evolve(), the decoding is done in parallel using threads, and the user must guarantee that the decoder is THREAD-SAFE. If such property cannot be held, we suggest using a single thread for optimization.
Parameters
pr_type type of path relinking to be performed. See PathRelinking::Type.
dist a pointer to a functor/object to compute the distance between two chromosomes. This object must be inherited from NSBRKGA::DistanceFunctionBase and implement its methods.
max_time aborts path relinking when reach max_time. If max_time <= 0, no limit is imposed. Default: 0 (no limit).
percentage defines the size, in percentage, of the path to build. Default: 1.0 (100%).
Returns
A PathRelinking::PathRelinkingResult depending on the relink status.
Exceptions
std::range_error if the percentage or size of the path is not in (0, 1].
Definition at line 3787 of file nsbrkga.hpp.
References NSBRKGA::PathRelinking::ALLOCATION, NSBRKGA::NsbrkgaParams::num_incumbent_solutions, NSBRKGA::NsbrkgaParams::num_independent_populations, and NSBRKGA::PathRelinking::PERMUTATION.
pathRelink() [2/2]
template<class Decoder > PathRelinking::PathRelinkingResult NSBRKGA::NSBRKGA< Decoder >::pathRelink (std::shared_ptr< DistanceFunctionBase > dist, long max_time = 0, double percentage = 1.0)
Performs path relinking between elite solutions that are, at least, a given minimum distance between themselves.
This method uses all parameters supplied in the constructor. In particular, the block size is computed by \(\lceil \alpha \times \sqrt{p} \rceil\) where \(\alpha\) is NsbrkgaParams::alpha_block_size and \(p\) is NsbrkgaParams::population_size. If the size is larger than the chromosome size, the size is set to half of the chromosome size.
Please, refer to pathRelink() for details.
Parameters
dist a pointer to a functor/object to compute the distance between two chromosomes. This object must be inherited from NSBRKGA::DistanceFunctionBase and implement its methods.
max_time aborts path relinking when reach max_time. If max_time <= 0, no limit is imposed. Default: 0 (no limit).
percentage defines the size, in percentage, of the path to build. Default: 1.0 (100%).
Returns
A PathRelinking::PathRelinkingResult depending on the relink status.
Exceptions
std::range_error if the percentage or size of the path is not in (0, 1].
Definition at line 3949 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::pr_type.
permutationPathRelink()
template<class Decoder > std::pair< std::vector< double >, Chromosome > NSBRKGA::NSBRKGA< Decoder >::permutationPathRelink (const std::pair< std::vector< double >, Chromosome > & solution1, const std::pair< std::vector< double >, Chromosome > & solution2, long max_time, double percentage, std::vector< std::pair< std::vector< double >, Chromosome >> & best_solutions) protected
Performs the permutation-based path relinking.
In this method, the permutation induced by the keys in the guide solution is used to change the order of the keys in the permutation induced by the base solution.
This method is a multi-thread implementation. Instead of to build and decode each chromosome one at a time, the method builds a list of candidates, altering the alleles/keys according to the guide solution, and then decode all candidates in parallel. Note that O(chromosome_size^2) additional memory is necessary to build the candidates, which can be costly if the chromosome_size is very large.
The path relinking is performed by changing the order of each allele of base chromosome for the correspondent one in the guide chromosome.
Parameters
solution1 first solution (fitness–chromosome pair).
solution2 second solution (fitness–chromosome pair).
max_time abort path relinking when reach max_time. If max_time <= 0, no limit is imposed.
percentage define the size, in percentage, of the path to build.
[out] best_solutions the best solutions found in the search.
Returns
the best solution found in the search.
Definition at line 4216 of file nsbrkga.hpp.
References NSBRKGA::MAXIMIZE, and NSBRKGA::NsbrkgaParams::num_incumbent_solutions.
polynomialMutation() [1/3]
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::polynomialMutation (double & allele) private
Definition at line 3561 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::mutation_probability.
polynomialMutation() [2/3]
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::polynomialMutation (double & allele, double mutation_probability) private
Definition at line 3552 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::mutation_distribution.
polynomialMutation() [3/3]
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::polynomialMutation (double & allele, double mutation_probability, double mutation_distribution) private
Applies polynomial mutation to a single allele value.
Performs polynomial mutation on the given allele, a variation operator commonly used in multi-objective evolutionary algorithms (e.g., NSGA-II). The mutation perturbs the allele value using a polynomial probability distribution, where the shape of the distribution is controlled by the mutation distribution index.
The mutation is applied probabilistically based on the given mutation probability. When triggered, a random perturbation (delta) is computed using the polynomial distribution, which favors small perturbations near the original value while still allowing larger changes.
The resulting allele value is clamped to the valid range [0.0, 1.0), where the upper bound is set to RAND_MAX / (RAND_MAX + 1.0) to ensure the allele remains strictly less than 1.0.
Parameters
[in,out] allele The allele value to be mutated, expected to be in the range [0.0, 1.0). Modified in place if mutation is applied.
[in] mutation_probability The probability of applying the mutation to the allele (value in [0.0, 1.0]).
[in] mutation_distribution The distribution index (eta_m) that controls the shape of the polynomial distribution. Higher values produce perturbations closer to the original value. Note: this parameter is unused in the body; the member variable this->params.mutation_distribution is used instead.
Definition at line 3514 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::mutation_distribution.
rand01()
template<class Decoder > double NSBRKGA::NSBRKGA< Decoder >::rand01 inline protected
Generates a random double-precision floating-point number uniformly distributed in the range [0, 1).
Uses std::generate_canonical to produce a high-precision random value with as many random bits as the double type supports. This method is preferred over manual scaling of the RNG output to avoid precision issues that can occur on certain platforms (e.g., Linux).
Returns
A uniformly distributed random double in the interval [0, 1).
Definition at line 4653 of file nsbrkga.hpp.
randInt()
template<class Decoder > uint_fast32_t NSBRKGA::NSBRKGA< Decoder >::randInt (const uint_fast32_t n) inline protected
Generates a uniformly distributed random integer in the range [0, n].
Uses a rejection sampling technique adapted from Magnus Jonsson (magnu.nosp@m.s@sm.nosp@m.artel.nosp@m.ectr.nosp@m.onix..nosp@m.com) to produce an unbiased random integer. The method works by first computing a bitmask that covers all bits used by the value n, then repeatedly drawing random values masked to those bits until the result falls within the desired range [0, n]. This avoids the modulo bias that would result from a simple modulus operation.
Template Parameters
Decoder The decoder type used by the NSBRKGA framework.
Parameters
n The upper bound (inclusive) of the random integer range. Must be a non-negative value representable by uint_fast32_t.
Returns
A uniformly distributed random integer in the range [0, n].
Note
This method is specific to uint_fast32_t types (up to 32-bit values).
The expected number of iterations is at most 2, since the mask ensures at least half of the drawn values fall within [0, n].
Definition at line 4687 of file nsbrkga.hpp.
reset()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::reset (double intensity = 0.5, unsigned population_index = std::numeric_limits<unsigned>::infinity())
Resets all populations with brand new keys.
All warm-start solutions provided setInitialPopulation() are discarded. You may use injectChromosome() to insert those solutions again.
Parameters
intensity the intensity of the reset.
population_index the index of the population to be reset. If population_index >= num_independent_populations, all populations are reset.
Exceptions
std::runtime_error if the algorithm is not initialized.
Definition at line 3051 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::num_independent_populations, and NSBRKGA::NsbrkgaParams::population_size.
selectParents()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::selectParents (const Population & curr, const size_t & chr, const bool use_best_individual = false) private
Definition at line 3433 of file nsbrkga.hpp.
References NSBRKGA::Population::fitness, NSBRKGA::Population::num_elites, and NSBRKGA::NsbrkgaParams::total_parents.
setBiasCustomFunction()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::setBiasCustomFunction (const std::function< double(const unsigned)> & func)
Sets a custom bias function used to build the probabilities.
It must be a positive non-increasing function, i.e. \(f: \mathbb{N}^+ \to \mathbb{R}^+\) such that \(f(i) \ge 0\) and \(f(i) \ge f(i+1)\) for \(i \in [1..total\_parents]\). For example
setBiasCustomFunction(
    [](const unsigned x) {
        return 1.0 / (x * x);
    }
);
sets an inverse quadratic function.
Parameters
func a reference to a unary positive non-increasing function.
Exceptions
std::runtime_error in case the function is not a non-decreasing positive function.
Definition at line 3002 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::bias_type, NSBRKGA::CUSTOM, and NSBRKGA::NsbrkgaParams::total_parents.
setDiversityCustomFunction()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::setDiversityCustomFunction (const std::function< double(const std::vector< std::vector< double >> &)> & func)
Sets a custom diversity function used to build the elite set.
Definition at line 3031 of file nsbrkga.hpp.
setInitialPopulations()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::setInitialPopulations (const std::vector< std::vector< Chromosome >> & populations)
Sets individuals to initial population.
Set initial individuals into the population to work as warm-starters. Such individuals can be obtained from solutions of external procedures such as fast heuristics, other metaheuristics, or even relaxations from a mixed integer programming model that models the problem.
All given solutions are assigned to one population only. Therefore, the maximum number of solutions is the size of the populations.
Parameters
populations a set of individuals encoded as Chromosomes.
Exceptions
std::runtime_error if the number of given chromosomes is larger than the population size; if the sizes of the given chromosomes do not match with the required chromosome size.
Definition at line 3231 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::num_independent_populations, and NSBRKGA::NsbrkgaParams::population_size.
shake()
template<class Decoder > void NSBRKGA::NSBRKGA< Decoder >::shake (double intensity = 0.5, double distribution = 20.0, unsigned population_index = std::numeric_limits<unsigned>::infinity())
Performs a shaking in the chosen population.
Parameters
intensity the intensity of the shaking.
distribution the distribution of the shaking.
population_index the index of the population to be shaken. If population_index >= num_independent_populations, all populations are shaken.
Exceptions
std::runtime_error if the algorithm is not initialized.
Definition at line 3385 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::num_independent_populations, and NSBRKGA::NsbrkgaParams::population_size.
updateIncumbentSolutions() [1/2]
template<class Decoder > bool NSBRKGA::NSBRKGA< Decoder >::updateIncumbentSolutions (const std::vector< std::pair< std::vector< double >, Chromosome >> & new_solutions) protected
Updates the incumbent (best known) solutions with new candidate solutions.
This is a convenience member function that delegates to the static version of updateIncumbentSolutions, passing the instance's incumbent solutions, optimization senses, and the configured maximum number of incumbent solutions.
Template Parameters
Decoder The decoder class used to evaluate chromosomes.
Parameters
new_solutions A vector of pairs, where each pair contains an objective values vector and its corresponding chromosome, representing the new candidate solutions to be considered for inclusion in the incumbent set.
Returns
True if the incumbent solutions were updated (i.e., at least one new solution was added or replaced an existing one); false otherwise.
Definition at line 4632 of file nsbrkga.hpp.
References NSBRKGA::NsbrkgaParams::num_incumbent_solutions.
updateIncumbentSolutions() [2/2]
template<class Decoder > bool NSBRKGA::NSBRKGA< Decoder >::updateIncumbentSolutions (std::vector< std::pair< std::vector< double >, Chromosome >> & incumbent_solutions, const std::vector< std::pair< std::vector< double >, Chromosome >> & new_solutions, const std::vector< Sense > & senses, const std::size_t max_num_solutions = 0) static protected
Definition at line 4548 of file nsbrkga.hpp.
References NSBRKGA::Population::dominates().
Member Data Documentation
bias_function
template<class Decoder > std::function<double(const unsigned)> NSBRKGA::NSBRKGA< Decoder >::bias_function protected
Reference for the bias function.
Definition at line 2313 of file nsbrkga.hpp.
CHROMOSOME_SIZE
template<class Decoder > const unsigned NSBRKGA::NSBRKGA< Decoder >::CHROMOSOME_SIZE protected
Number of genes in the chromosome.
Definition at line 2275 of file nsbrkga.hpp.
current
template<class Decoder > std::vector<std::shared_ptr<Population> > NSBRKGA::NSBRKGA< Decoder >::current protected
Current populations.
Definition at line 2310 of file nsbrkga.hpp.
decoder
template<class Decoder > Decoder& NSBRKGA::NSBRKGA< Decoder >::decoder protected
Reference to the problem-dependent Decoder.
Definition at line 2298 of file nsbrkga.hpp.
diversity_function
template<class Decoder > std::function<double(const std::vector<std::vector<double>> &)> NSBRKGA::NSBRKGA< Decoder >::diversity_function protected
Reference for the diversity function.
Definition at line 2317 of file nsbrkga.hpp.
evolutionary_mechanism_on
template<class Decoder > bool NSBRKGA::NSBRKGA< Decoder >::evolutionary_mechanism_on protected
If false, no evolution is performed but only chromosome decoding. Very useful to emulate a multi-start algorithm.
Definition at line 2285 of file nsbrkga.hpp.
incumbent_solutions
template<class Decoder > std::vector<std::pair<std::vector<double>, Chromosome> > NSBRKGA::NSBRKGA< Decoder >::incumbent_solutions protected
The current best solutions.
Definition at line 2342 of file nsbrkga.hpp.
initial_populations
template<class Decoder > bool NSBRKGA::NSBRKGA< Decoder >::initial_populations protected
Indicates if initial populations are set.
Definition at line 2333 of file nsbrkga.hpp.
initialized
template<class Decoder > bool NSBRKGA::NSBRKGA< Decoder >::initialized protected
Indicates if the algorithm was proper initialized.
Definition at line 2336 of file nsbrkga.hpp.
max_num_elites
template<class Decoder > unsigned NSBRKGA::NSBRKGA< Decoder >::max_num_elites protected
Maximum number of elite individuals in each population.
Definition at line 2281 of file nsbrkga.hpp.
MAX_THREADS
template<class Decoder > const unsigned NSBRKGA::NSBRKGA< Decoder >::MAX_THREADS protected
Number of threads for parallel decoding.
Definition at line 2291 of file nsbrkga.hpp.
min_num_elites
template<class Decoder > unsigned NSBRKGA::NSBRKGA< Decoder >::min_num_elites protected
Minimum number of elite individuals in each population.
Definition at line 2278 of file nsbrkga.hpp.
OPT_SENSES
template<class Decoder > const std::vector<Sense> NSBRKGA::NSBRKGA< Decoder >::OPT_SENSES protected
Indicates whether we are maximizing or minimizing each objective.
Definition at line 2272 of file nsbrkga.hpp.
params
template<class Decoder > NsbrkgaParams NSBRKGA::NSBRKGA< Decoder >::params protected
The BRKGA and IPR hyper-parameters.
Definition at line 2269 of file nsbrkga.hpp.
parents_indexes
template<class Decoder > std::vector<unsigned> NSBRKGA::NSBRKGA< Decoder >::parents_indexes protected
Used to select the parents for the mating.
Definition at line 2327 of file nsbrkga.hpp.
parents_ordered
template<class Decoder > std::vector<std::pair<std::vector<double>, unsigned> > NSBRKGA::NSBRKGA< Decoder >::parents_ordered protected
Defines the order of parents during the mating.
Definition at line 2330 of file nsbrkga.hpp.
pr_start_time
template<class Decoder > std::chrono::system_clock::time_point NSBRKGA::NSBRKGA< Decoder >::pr_start_time protected
Holds the start time for a call of the path relink procedure.
Definition at line 2339 of file nsbrkga.hpp.
previous
template<class Decoder > std::vector<std::shared_ptr<Population> > NSBRKGA::NSBRKGA< Decoder >::previous protected
Previous populations.
Definition at line 2307 of file nsbrkga.hpp.
rng
template<class Decoder > std::mt19937 NSBRKGA::NSBRKGA< Decoder >::rng protected
Mersenne twister random number generator.
Definition at line 2301 of file nsbrkga.hpp.
shuffled_individuals
template<class Decoder > std::vector<unsigned> NSBRKGA::NSBRKGA< Decoder >::shuffled_individuals protected
Used to shuffled individual/chromosome indices during the selection.
Definition at line 2324 of file nsbrkga.hpp.
total_bias_weight
template<class Decoder > double NSBRKGA::NSBRKGA< Decoder >::total_bias_weight protected
Holds the sum of the results of each raking given a bias function. This value is needed to normalization.
Definition at line 2321 of file nsbrkga.hpp.
The documentation for this class was generated from the following file:
/home/luishpmendes/UNICAMP/Doutorado/nsbrkga/nsbrkga/nsbrkga.hpp