NS-BRKGA: NSBRKGA::Population Class Reference
NSBRKGA::Population Class Reference
Internal container for one population of chromosomes.
#include <nsbrkga.hpp>
Public Member Functions
Default constructors and destructor
Population (const unsigned chr_size, const unsigned pop_size, std::function< double(const std::vector< std::vector< double >> &)> &diversity_function, const unsigned min_num_elites, const unsigned max_num_elites)
Default constructor.
Population (const Population &other)
Copy constructor.
Population & operator= (const Population &)=default
Assignment operator for compliance.
~Population ()=default
Destructor.
Simple access methods
unsigned getChromosomeSize () const
Returns the size of each chromosome.
unsigned getPopulationSize () const
Returns the size of the population.
double operator() (const unsigned chromosome, const unsigned allele) const
Returns a copy of an allele for a given chromosome.
double & operator() (const unsigned chromosome, const unsigned allele)
Returns a reference for an allele for a given chromosome.
Chromosome & operator() (unsigned chromosome)
Returns a reference to a chromosome.
Special access methods
These methods REQUIRE fitness to be sorted, and thus a call to sortFitness() beforehand.
std::vector< std::vector< double > > getBestFitnesses (const std::vector< Sense > &senses) const
Returns the best fitnesses in this population.
std::vector< Chromosome > getBestChromosomes (const std::vector< Sense > &senses) const
Returns the best chromosomes in this population.
std::vector< double > getFitness (const unsigned i) const
Returns the fitness of chromosome i.
Chromosome & getChromosome (unsigned i)
Returns a reference to the i-th best chromosome.
const Chromosome & getChromosome (const unsigned i) const
Returns a const reference to the i-th best chromosome.
void updateNumElites ()
Updates the number of elite individuals based on diversity function.
Public Attributes
Data members
std::vector< Chromosome > population
All chromosomes in this population. Index order matches fitness.
std::vector< std::pair< std::vector< double >, unsigned > > fitness
Sorted fitness table. Each entry is (objective_values, raw_index) where raw_index identifies the chromosome in population. Entries are sorted best-to-worst after each call to sortFitness().
unsigned min_num_fronts
Minimum number of non-dominated fronts observed across all generations.
unsigned max_num_fronts
Maximum number of non-dominated fronts observed across all generations.
unsigned num_non_dominated
Number of non-dominated individuals in the current generation (i.e., the size of Pareto front 0).
unsigned num_fronts
Total number of distinct non-dominated fronts in the current generation.
std::function< double(const std::vector< std::vector< double >> &)> & diversity_function
Diversity function used to determine the dynamic elite-set size.
unsigned min_num_elites
Hard lower bound on the number of elite individuals.
unsigned max_num_elites
Hard upper bound on the number of elite individuals.
unsigned num_elites
Current number of elite individuals (between min and max, inclusive).
Other methods
void sortFitness (const std::vector< Sense > &senses)
Sorts fitness by its first parameter according to the senses.
void setFitness (const unsigned chromosome, const std::vector< double > values)
Sets the fitness of chromosome.
static bool betterThan (const double &a1, const double &a2, const Sense &sense)
Returns true if a1 is better than a2.
static bool dominates (const std::vector< double > &a1, const std::vector< double > &a2, const std::vector< Sense > &senses)
Checks if a1 dominates a2 based on the provided optimization senses.
template<class T >
static std::vector< std::vector< std::pair< std::vector< double >, T > > > nonDominatedSort (const std::vector< std::pair< std::vector< double >, T >> &fitness, const std::vector< Sense > &senses)
template<class T >
static void crowdingSort (std::vector< std::pair< std::vector< double >, T >> &fitness)
template<class T >
static std::pair< unsigned, unsigned > sortFitness (std::vector< std::pair< std::vector< double >, T >> &fitness, const std::vector< Sense > &senses)
Detailed Description
Internal container for one population of chromosomes.
Population holds a generation's worth of chromosomes together with their decoded fitness vectors. It provides the sorting, dominance-checking, and elite-set management operations needed by the NSBRKGA engine.
Warning
This class is internal to the framework. User code should access chromosomes and fitness values through the public NSBRKGA interface (e.g., NSBRKGA::getChromosome(), NSBRKGA::getFitness(), NSBRKGA::getIncumbentSolutions()), not by manipulating Population objects directly.
Multi-objective sorting:
Fitness entries are sorted by non-dominated rank (front index) and, within each front, by crowding distance (descending). The combinedsorting is performed in \(O(N \cdot F \cdot \log F)\)-ish time where N is the population size and F is the number of fronts.
Non-dominated individuals in the first front (rank 0) are placed at indices 0..num_non_dominated-1 after sorting.
See also
NSBRKGA::NSBRKGA
Definition at line 674 of file nsbrkga.hpp.
Constructor & Destructor Documentation
Population() [1/2]
NSBRKGA::Population::Population (const unsigned chr_size, const unsigned pop_size, std::function< double(const std::vector< std::vector< double >> &)> & diversity_function, const unsigned min_num_elites, const unsigned max_num_elites) inline
Default constructor.
Parameters
chr_size size of chromosome.
pop_size size of population.
diversity_function diversity function.
min_num_elites minimum number of elite individuals.
max_num_elites maximum number of elite individuals.
Exceptions
std::range_error if population size or chromosome size is zero.
Definition at line 725 of file nsbrkga.hpp.
Population() [2/2]
NSBRKGA::Population::Population (const Population & other) inline
Copy constructor.
Definition at line 744 of file nsbrkga.hpp.
~Population()
NSBRKGA::Population::~Population () default
Destructor.
Member Function Documentation
betterThan()
static bool NSBRKGA::Population::betterThan (const double & a1, const double & a2, const Sense & sense) inline static
Returns true if a1 is better than a2.
This method depends on the optimization senses. When the optimization sense is Sense::MINIMIZE, a1 < a2 will return true, otherwise false. The opposite happens for Sense::MAXIMIZE. The comparisons are made using an epsilon value to cater for floating point precision issues.
Parameters
a1 First comparison value
a2 Second comparison value
sense The optimization sense
Returns
true if a1 is better than a2 based on the optimization sense, otherwise false
Definition at line 942 of file nsbrkga.hpp.
References NSBRKGA::MINIMIZE.
Referenced by dominates(), and nonDominatedSort().
crowdingSort()
template<class T > static void NSBRKGA::Population::crowdingSort (std::vector< std::pair< std::vector< double >, T >> & fitness) inline static
Definition at line 1101 of file nsbrkga.hpp.
References fitness.
dominates()
static bool NSBRKGA::Population::dominates (const std::vector< double > & a1, const std::vector< double > & a2, const std::vector< Sense > & senses) inline static
Checks if a1 dominates a2 based on the provided optimization senses.
An item a1 is said to dominate another item a2 if it is at least as good as a2 in all respects (as per the senses) and strictly better in at least one respect.
Parameters
a1 The first fitness vector.
a2 The second fitness vector.
senses The vector of optimization senses to apply for the domination check.
Returns
true if a1 dominates a2 according to the given optimization senses.
Definition at line 964 of file nsbrkga.hpp.
References betterThan().
Referenced by NSBRKGA::NSBRKGA< Decoder >::dominates(), nonDominatedSort(), and NSBRKGA::NSBRKGA< Decoder >::updateIncumbentSolutions().
getBestChromosomes()
std::vector<Chromosome> NSBRKGA::Population::getBestChromosomes (const std::vector< Sense > & senses) const inline
Returns the best chromosomes in this population.
This method requires fitness to be sorted, and thus a call to sortFitness() beforehand. It performs a non-dominated sort of the fitness, and then returns the first (i.e., best) front of solutions' chromosomes.
Parameters
senses A reference to a vector of Sense objects that is used for non-dominated sorting.
Returns
A vector of Chromosome representing the best chromosomes.
Exceptions
std::runtime_error if the resulting fronts vector is empty.
Definition at line 856 of file nsbrkga.hpp.
getBestFitnesses()
std::vector<std::vector<double> > NSBRKGA::Population::getBestFitnesses (const std::vector< Sense > & senses) const inline
Returns the best fitnesses in this population.
This method requires fitness to be sorted, and thus a call to sortFitness() beforehand. It performs a non-dominated sort of the fitness, and returns the first (i.e., best) front of solutions' fitnesses.
Parameters
senses A reference to a vector of Sense objects that is used for non-dominated sorting.
Returns
A vector of vector doubles representing the best fitnesses.
Exceptions
std::runtime_error if the resulting fronts vector is empty.
Definition at line 823 of file nsbrkga.hpp.
getChromosome() [1/2]
const Chromosome& NSBRKGA::Population::getChromosome (const unsigned i) const inline
Returns a const reference to the i-th best chromosome.
Definition at line 887 of file nsbrkga.hpp.
getChromosome() [2/2]
Chromosome& NSBRKGA::Population::getChromosome (unsigned i) inline
Returns a reference to the i-th best chromosome.
Definition at line 882 of file nsbrkga.hpp.
Referenced by NSBRKGA::NSBRKGA< Decoder >::evolution(), and updateNumElites().
getChromosomeSize()
unsigned NSBRKGA::Population::getChromosomeSize () const inline
Returns the size of each chromosome.
Definition at line 764 of file nsbrkga.hpp.
getFitness()
std::vector<double> NSBRKGA::Population::getFitness (const unsigned i) const inline
Returns the fitness of chromosome i.
Definition at line 877 of file nsbrkga.hpp.
getPopulationSize()
unsigned NSBRKGA::Population::getPopulationSize () const inline
Returns the size of the population.
Definition at line 769 of file nsbrkga.hpp.
nonDominatedSort()
template<class T > static std::vector<std::vector<std::pair<std::vector<double>, T> > > NSBRKGA::Population::nonDominatedSort (const std::vector< std::pair< std::vector< double >, T >> & fitness, const std::vector< Sense > & senses) inline static
Definition at line 988 of file nsbrkga.hpp.
References betterThan(), dominates(), and fitness.
operator()() [1/3]
double& NSBRKGA::Population::operator() (const unsigned chromosome, const unsigned allele) inline
Returns a reference for an allele for a given chromosome.
Usually used to set the allele value.
Parameters
chromosome index of desired chromosome.
allele index of desired allele.
Returns
a reference of the allele value.
Definition at line 789 of file nsbrkga.hpp.
operator()() [2/3]
double NSBRKGA::Population::operator() (const unsigned chromosome, const unsigned allele) const inline
Returns a copy of an allele for a given chromosome.
Parameters
chromosome index of desired chromosome.
allele index of desired allele.
Returns
a copy of the allele value.
Definition at line 777 of file nsbrkga.hpp.
operator()() [3/3]
Chromosome& NSBRKGA::Population::operator() (unsigned chromosome) inline
Returns a reference to a chromosome.
Parameters
chromosome index of desired chromosome.
Returns
a reference to chromosome.
Definition at line 798 of file nsbrkga.hpp.
operator=()
Population& NSBRKGA::Population::operator= (const Population &) default
Assignment operator for compliance.
setFitness()
void NSBRKGA::Population::setFitness (const unsigned chromosome, const std::vector< double > values) inline
Sets the fitness of chromosome.
Parameters
chromosome index of chromosome.
values fitness values.
Definition at line 1213 of file nsbrkga.hpp.
Referenced by NSBRKGA::NSBRKGA< Decoder >::evolution().
sortFitness() [1/2]
void NSBRKGA::Population::sortFitness (const std::vector< Sense > & senses) inline
Sorts fitness by its first parameter according to the senses.
Parameters
senses Optimization senses.
Definition at line 1194 of file nsbrkga.hpp.
References updateNumElites().
sortFitness() [2/2]
template<class T > static std::pair<unsigned, unsigned> NSBRKGA::Population::sortFitness (std::vector< std::pair< std::vector< double >, T >> & fitness, const std::vector< Sense > & senses) inline static
Definition at line 1158 of file nsbrkga.hpp.
References fitness.
Referenced by NSBRKGA::NSBRKGA< Decoder >::evolution().
updateNumElites()
void NSBRKGA::Population::updateNumElites () inline
Updates the number of elite individuals based on diversity function.
The method initially sets the number of elite individuals to the minimum value. It calculates the diversity of the first set of elites, then iteratively adds the next individuals and recalculates diversity, updating the number of elites if diversity is increased.
Definition at line 900 of file nsbrkga.hpp.
References diversity_function, getChromosome(), max_num_elites, and num_elites.
Referenced by sortFitness().
Member Data Documentation
diversity_function
std::function<double(const std::vector<std::vector<double>> &)>& NSBRKGA::Population::diversity_function
Diversity function used to determine the dynamic elite-set size.
Definition at line 701 of file nsbrkga.hpp.
Referenced by updateNumElites().
fitness
std::vector<std::pair<std::vector<double>, unsigned> > NSBRKGA::Population::fitness
Sorted fitness table. Each entry is (objective_values, raw_index) where raw_index identifies the chromosome in population. Entries are sorted best-to-worst after each call to sortFitness().
Definition at line 684 of file nsbrkga.hpp.
Referenced by crowdingSort(), NSBRKGA::NSBRKGA< Decoder >::evolution(), nonDominatedSort(), NSBRKGA::NSBRKGA< Decoder >::selectParents(), and sortFitness().
max_num_elites
unsigned NSBRKGA::Population::max_num_elites
Hard upper bound on the number of elite individuals.
Definition at line 707 of file nsbrkga.hpp.
Referenced by updateNumElites().
max_num_fronts
unsigned NSBRKGA::Population::max_num_fronts
Maximum number of non-dominated fronts observed across all generations.
Definition at line 690 of file nsbrkga.hpp.
min_num_elites
unsigned NSBRKGA::Population::min_num_elites
Hard lower bound on the number of elite individuals.
Definition at line 704 of file nsbrkga.hpp.
min_num_fronts
unsigned NSBRKGA::Population::min_num_fronts
Minimum number of non-dominated fronts observed across all generations.
Definition at line 687 of file nsbrkga.hpp.
num_elites
unsigned NSBRKGA::Population::num_elites
Current number of elite individuals (between min and max, inclusive).
Definition at line 710 of file nsbrkga.hpp.
Referenced by NSBRKGA::NSBRKGA< Decoder >::evolution(), NSBRKGA::NSBRKGA< Decoder >::selectParents(), and updateNumElites().
num_fronts
unsigned NSBRKGA::Population::num_fronts
Total number of distinct non-dominated fronts in the current generation.
Definition at line 697 of file nsbrkga.hpp.
num_non_dominated
unsigned NSBRKGA::Population::num_non_dominated
Number of non-dominated individuals in the current generation (i.e., the size of Pareto front 0).
Definition at line 694 of file nsbrkga.hpp.
population
std::vector<Chromosome> NSBRKGA::Population::population
All chromosomes in this population. Index order matches fitness.
Definition at line 679 of file nsbrkga.hpp.
Referenced by NSBRKGA::NSBRKGA< Decoder >::evolution().
The documentation for this class was generated from the following file:
/home/luishpmendes/UNICAMP/Doutorado/nsbrkga/nsbrkga/nsbrkga.hpp